### ISSUE TITLE
添加了新平台小游戏的adapter之后如何可以在发布界面选择新添加的平台进行发布？

### ISSUE THREAD

**Issue by eldn** [cocos-creator-packages/adapters#177]
添加了新平台小游戏的adapter之后如何可以在发布界面选择新添加的平台进行发布？

**Comment by eldn** [comment]
我目前使用的是ccc 2.3.2版本

**Comment by PPpro** [comment]
我们暂时不支持用户新增构建平台哈

**Comment by eldn** [comment]
呃，我这边计划是做个淘宝小程序（商家应用）的发布支持，接口基本适配完了，限制需要测试。
那有什么比较hack的方法让我用起来吗，项目要要跑起来才行。

**Comment by eldn** [comment]
> 我们暂时不支持用户新增构建平台哈

不增加到编辑器里也行，让我先用起来也行啊，江湖救急

**Comment by PPpro** [comment]
发微信平台吧，之后覆盖你的适配逻辑

**Comment by eldn** [comment]
> 发微信平台吧，之后覆盖你的适配逻辑
果然，好的，是个办法。
另外斗胆问下，你们这边有支持发布淘宝小程序（商家应用）的计划么？

**Comment by PPpro** [comment]
请问可以留意下你的联系方式吗

**Comment by eldn** [comment]
> 请问可以留一下你的联系方式吗，或者加我 微信号 PP_Pro

好的，加你微信了
